#!/bin/bash
 
line=$1
YELLOW='\033[1;33m'
NO_COLOR='\033[0m'
 
if [ -f $1 ]; then
  line=$(head -n 1 $1)
fi
  
regex=".*((\[[A-Z0-9]{2,}-[0-9]+\])|(\[NS\])).*"
 
if ! [[ $line =~ $regex ]]; then
  echo -e -n "${YELLOW}Your commit message does not contain a JIRA ticket.${NO_COLOR} Is this what you intended? [y|N] "
  read -n 1 REPLY < /dev/tty
  echo
  case $REPLY in
    y|Y)
      ;;
    *)
      echo "Aborting commit"
      exit 1
      ;;
  esac
fi
