#!/bin/bash
 
CURRENT_BRANCH=$(git branch --show-current)
YELLOW='\033[1;33m'
NO_COLOR='\033[0m'
 
if [ "$CURRENT_BRANCH" = "main" ] || [ "$CURRENT_BRANCH" = "master" ] || [ "$CURRENT_BRANCH" = "develop" ]; then
  echo -e -n "${YELLOW}You're about to commit on ${CURRENT_BRANCH}.${NO_COLOR} Is this what you intended? [y|N] "
  read -n 1 REPLY < /dev/tty
  echo
  case $REPLY in
    y|Y)
      ;;
    *)
      echo "Aborting commit"
      exit 1
      ;;
  esac
fi
